# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 226b598672da0a4c3f6fc664cca9f8e6a7e72f53b168a6d37b0dc2a14be4429983b75e3d5fe3e5ee071d96463175d18d16e9e9c8ef413d4d165fd9a90194b278

test:
  secret_key_base: ecdfd62550ba896bc25fd44436c64518c6f7e1f0d01cf7ed780cd4908495a457bf6827c1455ec1f2d5559bf07fa26341dd3a9722646e0bdbd7b2a5f6890b5f66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
